# Generated by Django 4.2.6 on 2023-10-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0002_userprofile_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='handphone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
