# Generated by Django 4.2.6 on 2023-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0003_alter_userprofile_email_alter_userprofile_handphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='handphone',
            field=models.IntegerField(default=1234567890),
        ),
    ]
