# Generated by Django 4.2.4 on 2023-10-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0006_userprofile_favorite_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
