# Generated by Django 4.2.4 on 2023-10-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_count_read'),
        ('rprofile', '0007_delete_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, to='main.book'),
        ),
    ]
