# Generated by Django 4.2.4 on 2023-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_remove_quotes_text_remove_quotes_user_profile_and_more'),
        ('rprofile', '0007_userprofile_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='text',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='bom.quotes'),
        ),
    ]
