# Generated by Django 4.2.8 on 2023-12-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0007_delete_userbook'),
        ('rprofile', '0008_remove_userprofile_text_userprofile_quotes'),
    ]

    operations = [
    ]
