# Generated by Django 4.2.8 on 2023-12-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0009_merge_20231220_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='quotes',
        ),
    ]
