# Generated by Django 4.2.4 on 2023-12-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0008_userprofile_favorite_books'),
        ('rprofile', '0010_remove_userprofile_quotes'),
    ]

    operations = [
    ]
