# Generated by Django 4.2.4 on 2023-10-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_read',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
