# Generated by Django 4.2.4 on 2023-10-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_user_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='index_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
