# Generated by Django 4.2.4 on 2023-10-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_index_key_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.URLField(default='https://img.freepik.com/premium-vector/open-blank-book-illustration-school-supply-back-school-open-book-icon-reading-writing_502505-530.jpg?w=2000', max_length=300),
        ),
    ]
