# Generated by Django 4.2.4 on 2023-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='text',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='quotes',
            name='quotes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
