# Generated by Django 4.2.8 on 2023-12-19 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bom', '0002_remove_quotes_text_remove_quotes_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quotes',
            field=models.TextField(default='quote'),
            preserve_default=False,
        ),
    ]
