# Generated by Django 4.2.4 on 2023-10-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rprofile', '0009_remove_userprofile_quotes_userprofile_quotes'),
        ('bom', '0002_remove_quotes_text_remove_quotes_user_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
